// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	domain "OctoQueue/internal/domain"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// TaskWriter is an autogenerated mock type for the TaskWriter type
type TaskWriter struct {
	mock.Mock
}

// DeleteTask provides a mock function with given fields: ctx, id
func (_m *TaskWriter) DeleteTask(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTask provides a mock function with given fields: ctx, p
func (_m *TaskWriter) UpdateTask(ctx context.Context, p domain.UpdateTaskParams) (*domain.Task, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *domain.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTaskParams) (*domain.Task, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.UpdateTaskParams) *domain.Task); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.UpdateTaskParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTaskStatus provides a mock function with given fields: ctx, id, status, nextRunAt
func (_m *TaskWriter) UpdateTaskStatus(ctx context.Context, id string, status string, nextRunAt *time.Time) error {
	ret := _m.Called(ctx, id, status, nextRunAt)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTaskStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, *time.Time) error); ok {
		r0 = rf(ctx, id, status, nextRunAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskWriter creates a new instance of TaskWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskWriter {
	mock := &TaskWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
