// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	slog "log/slog"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	storage "OctoQueue/internal/storage"
)

// TaskRequest is an autogenerated mock type for the TaskRequest type
type TaskRequest struct {
	mock.Mock
}

// GetTask provides a mock function with given fields: log, st
func (_m *TaskRequest) GetTask(log *slog.Logger, st storage.TaskRepository) http.HandlerFunc {
	ret := _m.Called(log, st)

	if len(ret) == 0 {
		panic("no return value specified for GetTask")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(*slog.Logger, storage.TaskRepository) http.HandlerFunc); ok {
		r0 = rf(log, st)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// ListTasks provides a mock function with given fields: log, st
func (_m *TaskRequest) ListTasks(log *slog.Logger, st storage.TaskRepository) http.HandlerFunc {
	ret := _m.Called(log, st)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(*slog.Logger, storage.TaskRepository) http.HandlerFunc); ok {
		r0 = rf(log, st)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// Status provides a mock function with given fields: log
func (_m *TaskRequest) Status(log *slog.Logger) http.HandlerFunc {
	ret := _m.Called(log)

	if len(ret) == 0 {
		panic("no return value specified for Status")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(*slog.Logger) http.HandlerFunc); ok {
		r0 = rf(log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// NewTaskRequest creates a new instance of TaskRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRequest {
	mock := &TaskRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
