// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	slog "log/slog"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	storage "OctoQueue/internal/storage"
)

// TaskExecutionRequest is an autogenerated mock type for the TaskExecutionRequest type
type TaskExecutionRequest struct {
	mock.Mock
}

// GetTaskExecutions provides a mock function with given fields: log, st
func (_m *TaskExecutionRequest) GetTaskExecutions(log *slog.Logger, st storage.ExecutionTracker) http.HandlerFunc {
	ret := _m.Called(log, st)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskExecutions")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(*slog.Logger, storage.ExecutionTracker) http.HandlerFunc); ok {
		r0 = rf(log, st)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// NewTaskExecutionRequest creates a new instance of TaskExecutionRequest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskExecutionRequest(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskExecutionRequest {
	mock := &TaskExecutionRequest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
