// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	slog "log/slog"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	storage "OctoQueue/internal/storage"
)

// UpdateTasks is an autogenerated mock type for the UpdateTasks type
type UpdateTasks struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: log, st
func (_m *UpdateTasks) CreateTask(log *slog.Logger, st storage.TaskRepository) http.HandlerFunc {
	ret := _m.Called(log, st)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(*slog.Logger, storage.TaskRepository) http.HandlerFunc); ok {
		r0 = rf(log, st)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// DeleteTask provides a mock function with given fields: log, st
func (_m *UpdateTasks) DeleteTask(log *slog.Logger, st storage.TaskWriter) http.HandlerFunc {
	ret := _m.Called(log, st)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(*slog.Logger, storage.TaskWriter) http.HandlerFunc); ok {
		r0 = rf(log, st)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// UpdateTask provides a mock function with given fields: log, st
func (_m *UpdateTasks) UpdateTask(log *slog.Logger, st storage.TaskWriter) http.HandlerFunc {
	ret := _m.Called(log, st)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 http.HandlerFunc
	if rf, ok := ret.Get(0).(func(*slog.Logger, storage.TaskWriter) http.HandlerFunc); ok {
		r0 = rf(log, st)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.HandlerFunc)
		}
	}

	return r0
}

// NewUpdateTasks creates a new instance of UpdateTasks. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpdateTasks(t interface {
	mock.TestingT
	Cleanup(func())
}) *UpdateTasks {
	mock := &UpdateTasks{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
