// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	storage "OctoQueue/internal/storage"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ExecutionTracker is an autogenerated mock type for the ExecutionTracker type
type ExecutionTracker struct {
	mock.Mock
}

// CreateExecution provides a mock function with given fields: ctx, p
func (_m *ExecutionTracker) CreateExecution(ctx context.Context, p storage.CreateExecutionParams) (*storage.TaskExecution, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateExecution")
	}

	var r0 *storage.TaskExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.CreateExecutionParams) (*storage.TaskExecution, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, storage.CreateExecutionParams) *storage.TaskExecution); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.TaskExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, storage.CreateExecutionParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FinishExecution provides a mock function with given fields: ctx, p
func (_m *ExecutionTracker) FinishExecution(ctx context.Context, p storage.FinishExecutionParams) (*storage.TaskExecution, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for FinishExecution")
	}

	var r0 *storage.TaskExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.FinishExecutionParams) (*storage.TaskExecution, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, storage.FinishExecutionParams) *storage.TaskExecution); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.TaskExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, storage.FinishExecutionParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListExecutions provides a mock function with given fields: ctx, taskID, limit
func (_m *ExecutionTracker) ListExecutions(ctx context.Context, taskID string, limit int) ([]*storage.TaskExecution, error) {
	ret := _m.Called(ctx, taskID, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListExecutions")
	}

	var r0 []*storage.TaskExecution
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) ([]*storage.TaskExecution, error)); ok {
		return rf(ctx, taskID, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int) []*storage.TaskExecution); ok {
		r0 = rf(ctx, taskID, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.TaskExecution)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = rf(ctx, taskID, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewExecutionTracker creates a new instance of ExecutionTracker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExecutionTracker(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExecutionTracker {
	mock := &ExecutionTracker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
