// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	storage "OctoQueue/internal/storage"
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// LockManager is an autogenerated mock type for the LockManager type
type LockManager struct {
	mock.Mock
}

// AcquireLock provides a mock function with given fields: ctx, taskID, workerID, ttl
func (_m *LockManager) AcquireLock(ctx context.Context, taskID string, workerID string, ttl time.Duration) (*storage.TaskLock, error) {
	ret := _m.Called(ctx, taskID, workerID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for AcquireLock")
	}

	var r0 *storage.TaskLock
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) (*storage.TaskLock, error)); ok {
		return rf(ctx, taskID, workerID, ttl)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) *storage.TaskLock); ok {
		r0 = rf(ctx, taskID, workerID, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.TaskLock)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, time.Duration) error); ok {
		r1 = rf(ctx, taskID, workerID, ttl)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CleanExpiredLocks provides a mock function with given fields: ctx
func (_m *LockManager) CleanExpiredLocks(ctx context.Context) (int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CleanExpiredLocks")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int64); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReleaseLock provides a mock function with given fields: ctx, taskID, workerID
func (_m *LockManager) ReleaseLock(ctx context.Context, taskID string, workerID string) error {
	ret := _m.Called(ctx, taskID, workerID)

	if len(ret) == 0 {
		panic("no return value specified for ReleaseLock")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, taskID, workerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewLockManager creates a new instance of LockManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLockManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *LockManager {
	mock := &LockManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
