// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	storage "OctoQueue/internal/storage"
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, p
func (_m *TaskRepository) CreateTask(ctx context.Context, p storage.CreateTaskParams) (*storage.Task, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *storage.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.CreateTaskParams) (*storage.Task, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, storage.CreateTaskParams) *storage.Task); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, storage.CreateTaskParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTaskByID provides a mock function with given fields: ctx, id
func (_m *TaskRepository) GetTaskByID(ctx context.Context, id string) (*storage.Task, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 *storage.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*storage.Task, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *storage.Task); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListTasks provides a mock function with given fields: ctx, p
func (_m *TaskRepository) ListTasks(ctx context.Context, p storage.ListTasksParams) ([]*storage.Task, error) {
	ret := _m.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []*storage.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, storage.ListTasksParams) ([]*storage.Task, error)); ok {
		return rf(ctx, p)
	}
	if rf, ok := ret.Get(0).(func(context.Context, storage.ListTasksParams) []*storage.Task); ok {
		r0 = rf(ctx, p)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*storage.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, storage.ListTasksParams) error); ok {
		r1 = rf(ctx, p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
